# -*- coding: utf-8 -*-
"""Semana1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z-MxcEP9BCuT3avf5WJv9nk3UZtxZ_Jr

# Instruções

- Antes de resolver esses exercícios, certifique-se que a configuração está correta (Python 3).

- Se estiver usando o Colab, faça uma cópia deste notebook antes de começar a repondê-lo.

![](http://professor.ufabc.edu.br/~ronaldo.prati/colab.png)

- Lembre-se de manter o nome do caderno com o mesmo nome original.

- Não apague nem introduza novas células neste notebook.

- Certifique-se que você preencheu todos os lugares que dizem \"YOUR CODE HERE\" ou \"YOUR ANSWER HERE\". Substitutua essa linha e também a linha `raise NotImplementedError()` pelo seu código.

- Depois de resolver os exercícios, para enviar a atividade, salve o notebook e o envie pelo moodle da disciplina. No colab, para exportar o notebook localmente, acesse `File->Download->Download .ipynb` ou `Arquivo->Baixar->Baixar .ipynb`

![](http://professor.ufabc.edu.br/~ronaldo.prati/submit.png)

# Exercício 1

Faça um programa que peça um número e armazene-o em uma variável. A seguir, mostre a mensagem "O número informado foi [número]"
"""

n1 = input("Digite um número : ")
print("O número informado foi",n1)

"""# Exercício 2

Faça um Programa que peça o raio de um círculo, calcule e mostre sua área.
Dica: para usar o valor de $\pi$, pesquise por `math.pi`.
"""

import math

n1 = float(input("Digite um valor para o raio do círculo : "))
n2 = math.pi*(math.pow(n1, 2))
print("A área do círculo é : ", n2)

"""# Exercício 3

Faça um Programa que peça 2 números inteiros e um número real. Calcule e mostre:

   - o produto do dobro do primeiro com metade do segundo .
   - a soma do triplo do primeiro com o terceiro.
   - o terceiro elevado ao cubo. 
"""

import math

n1 = int(input("Digite um número inteiro "))
n2 = int(input("Digite outro número inteiro "))
n3 = float(input("Digite um número real "))

n4 = (n1*2) * (n2/2)
n5 = (n1*3) + n3
n6 = math.pow(n3, 3)

print("O produto do dobro do primeiro com metade do segundo : ", n4)
print("A soma do triplo do primeiro com o terceiro : ", n5)
print("O terceiro elevado ao cubo : ", n6)

"""# Exercício 4

Faça um programa que pergunte quanto você ganha por hora e o número de horas trabalhadas na semana. Calcule e mostre o total do seu salário ao final de 4 semanas. 
"""

n1 = int(input("Quantas horas você trabalha por semana ? "))
n2 = float(input("Quanto você ganha por hora ? "))
n3 = n1*n2*4

print("O seu salário ao final de 4 semanas é de R$", n3)

"""# Exercício 5

Faça um programa que leia um número inteiro qualquer e que apresete, além do número informado, o seu antecessor e do seu sucessor.
"""

n1 = int(input("Digite um número : "))

print("O número digitado foi : ", n1)
print("Seu antecessor é : ", n1-1)
print("Seu sucessor é : ", n1+1)

"""# Exercício 6

Faça um programa que leia quatro notas, e seus respectivos pesos, e que apresente a média final simples e a média final ponderada.
"""

n1 = float(input("Digite a primeira nota : "))
n2 = float(input("Digite a segunda nota : "))
n3 = float(input("Digite a terceira nota : "))
n4 = float(input("Digite a quarta nota : "))

p1 = float(input("Digite o peso da primeira nota : "))
p2 = float(input("Digite o peso da segunda nota : "))
p3 = float(input("Digite o peso da terceira nota : "))
p4 = float(input("Digite o peso da quarta nota : "))

media_simples = (n1+n2+n3+n4)/4
media_ponderada = ((n1*p1) + (n2*p2) + (n3*p3) + (n4*p4))/(p1+p2+p3+p4)

print("Sua média final simples foi : ", media_simples)
print("Sua média final ponderada foi : ", media_ponderada)

"""# Exercício 7

Faça um programa para uma loja de tintas. O programa deverá pedir o tamanho em metros quadrados da área a ser pintada. Considere que a cobertura da tinta é de 1 litro para cada 12 metros quadrados e que a tinta é vendida em latas de 18 litros, que custam R$ 80,00. Informe ao usuário a quantidades de latas de tinta a serem compradas e o preço total. 
"""

metros_quadrados = int(input("Digite o número de metros quadrados da área a ser pintada : "))
litros = metros_quadrados*(1/12)
latas = litros/18
preco = latas*80

print("A localidade possui : ", metros_quadrados, " metros quadrados")
print("Serão necessários : ", litros, " litros")
print("Serão necessárias : ", latas, " latas")
print("Será gasto R$", preco)

"""# Exercício 8

Faça um Programa para uma loja de tintas. O programa deverá pedir o tamanho em metros quadrados da área a ser pintada. Considere que a cobertura da tinta é de 1 litro para cada 12 metros quadrados e que a tinta é vendida em latas de 18 litros, que custam R$ 80,00 ou em galões de 3,6 litros, que custam R$ 25,00.

Informe ao usuário as quantidades de tinta a serem compradas e os respectivos preços em 3 situações:

    - comprar apenas latas de 18 litros;
    - comprar apenas galões de 3,6 litros;
    - misturar latas e galões, de forma que o desperdício de tinta seja menor. 
    
Acrescente 10% de folga nos três casos (isto é, você deve adicionar 10% sobre o total de litros de tinta necessário) e sempre arredonde os valores para cima, isto é, considere latas cheias. 


"""

import math

metros_quadrados = float(input("Digite o número de metros quadrados da área a ser pintada : "))

litros = metros_quadrados/12 * 1.1

latas = math.ceil(litros/18)
preco = latas*80

galoes = math.ceil(litros/3.6)
preco2 = galoes*25

print("Você terá que comprar ", litros, " litro(s) de tinta")

print("Você terá gasto R$", preco, " caso compre latas de 18 litros")

print("Você terá gasto ", preco2, " caso compre galões de 3,6 litros")

latas_min = math.floor(litros/18)
sobra = litros - (latas_min *18)
galoes_sobra = math.ceil(sobra/3.6)

print("Misturando latas e galões, a quantidade de latas a ser comprada é",latas_min,"e de galões",galoes_sobra)
print("O preço total é R$",latas_min*80 + galoes_sobra*25)