# -*- coding: utf-8 -*-
"""Semana2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gemKdNe59UDQQoP8XMe8rjcZ8Cycvdvy

# Instruções

- Antes de resolver esses exercícios, certifique-se que a configuração está correta (Python 3).

- Se estiver usando o Colab, faça uma cópia deste notebook antes de começar a repondê-lo.

![](http://professor.ufabc.edu.br/~ronaldo.prati/colab.png)

- Lembre-se de manter o nome do caderno com o mesmo nome original.

- Não apague nem introduza novas células neste notebook.

- Certifique-se que você preencheu todos os lugares que dizem \"YOUR CODE HERE\" ou \"YOUR ANSWER HERE\". Substitutua essa linha e também a linha `raise NotImplementedError()` pelo seu código.

- Depois de resolver os exercícios, para enviar a atividade, salve o notebook e o envie pelo moodle da disciplina. No colab, para exportar o notebook localmente, acesse `File->Download->Download .ipynb` ou `Arquivo->Baixar->Baixar .ipynb`

![](http://professor.ufabc.edu.br/~ronaldo.prati/submit.png)

# Exercício 1

Faça um programa que receba dois números e, usando condicionais, mostre o maior. Se por acaso os dois números forem iguais, imprima a mensagem "Números iguais".
"""

n1 = input("Digite o primeiro número : ")
n2 = input("Digite o segundo número : ")

if n1>n2: 
  print("O primeiro número é maior que o segundo")
elif n1 == n2: 
  print("Ambos são iguais")
else: 
  print("O segundo número é maior que o primeiro")

"""# Exercício 2

Faça um programa que simule o lançamento de uma moeda, sorteando um número aleatório entre 0 e 1 (pesquise sobre a função `random`, da biblioteca `random`). Se o número sorteado for menor ou igual a 0.5, imprima "cara" e se for maior "coroa".
"""

import random 

n1 = random.random()

print(n1)

if n1 <= 0.5: 
  print("cara")
else: 
  print("coroa")

"""# Exercício 3

Faca um programa que simule um "prova de matemática" para crianças que estão aprendendo a somar n  ́umeros inteiros menores do que 100. Sorteie um número aleatório entre 0 e 100 (procure pela função `randint` da biblioteca `random`), imprime esse número, e peça para o usuário digitar qual número precisa ser somado para completar 100. O seu programa deve verificar se o número digitado está correto ou não (isto é, se a soma do número sorteado com o digitado é igual a 100.
"""

import random 

n1 = random.randint(0, 100)

print("O valor aleatório é ", n1)

n2 = int(input("Digite o valor que deve ser somado para completar 100 : "))

if n1+n2 == 100: 
  print("O valor está correto")
else: 
  print("O valor está incorreto")

"""# Exercício 4

Uma empresa decide dar um aumento aos seus funcionários de acordo com uma tabela
que considera o salário atual e o tempo de serviço de cada funcionário. Os funcionários
com menor salário terão um aumento proporcionalmente maior do que os funcionários
com um salário maior, e conforme o tempo de serviço na empresa, cada funcionário irá receber um bônus adicional de salário. Faça um programa que leia:


- o valor do salário atual do funcionário;
- o tempo de serviço desse funcionário na empresa (número de anos de trabalho na empresa).


Use as tabelas a seguir para calcular o salário reajustado deste funcionário e imprima o
valor do salário final reajustado, ou uma mensagem caso o funcionário não tenha direito
a nenhum aumento.

|Salário Atual | Reajuste |  
|-------------:|---------:|
| até 1.500,00 |  25%     |
| até 2.500,00 |  20%     |
| até 3.500,00 |  15%     |
| até 5.000,00 |  10%     |
| acima de 5.000,00 | sem aumento |

| Tempo de Serviço  | Bônus  |
|------------------:|-------:|
| menos de 3 anos   | sem bonus |
| de 3 a 5 anos     | 200,00    |
| de 5 a 8 anos     | 300,00    |
| de 8 a 10 anos    | 400,00    |
| acima de 10 anos  | 500,00    |


"""

n1 = int(input("Qual o seu salário atual ? "))

if n1 < 1500:
  n2 = n1 + (1/4)*n1
elif n1 >= 1500 and n1 < 2500: 
  n2 = n1 + (1/5)*n1
elif n1 >= 2500 and n1 < 3500: 
  n2 = n1 + (3/20)*n1
elif n1 >= 3500 and n1 < 5000: 
  n2 = n1 + (1/10)*n1
else: 
  print("Não há aumento")

print(n2)

n3 = int(input("Quanto tempo de contribuição você possui ? "))

n4 = 0

if n3 < 3: 
  print("Não há bônus")
elif n3>=3 and n3<5: 
  n4 = n4 + 200
elif n3>=5 and n3<8: 
  n4 = n4 + 300
elif n3>=8 and n3<10: 
  n4 = n4 + 400 
else: 
  n4 = n4 + 500

print(n4)

salario = n2+n4

print(salario)

"""# Exercício 5

Faça uma função para verificar se um número passado como parâmetro ́e zero, positivo ou negativo. Se o número for positivo, a função deve retornar 1, se for negativo, retornar -1, e se for 0, retornar 0. 

Inclua também código (fora da função) que leia um número digitado pelo usuário, faça uma chamada para a função, e imprima as mensagens:

- Número digitado é negativo
- Número digitado é positivo
- Número digitado é zero

de acordo com o retorno da função.
"""

def verifica(x): 
  if x==0:
    return ("0") 
  elif x>0: 
    return("1")
  else: 
    return("-1")

x = int(input("Digite o valor "))

res = verifica(x)

print(res)

if x==0: 
  print("Número digitado é zero")
elif x>0: 
  print("Número digitado é positivo")
else: 
  print("Número digitado é negativo")

"""# Exercício 6

Sejam $a$ e $b$ os catetos de um triângulo retângulo, onde a hipotenusa  ́e obtida pela e:
$hipotenusa = \sqrt{a^2 + b^2}$. Faça uma funçãoo que receba os valores de $a$ e $b$, calcule e retorne o valor da hipotenusa através da equação.

Fora da função, faça um programa que leia os valores de $a$ e $b$, e imprima o valor da $hipotenusa$.
"""

import math

def formula(a, b):
  return math.sqrt(a*a + b*b)

a = int(input("Digite um valor para o cateto "))
b = int(input("Digite o valor do outro cateto "))

c = formula(a, b)

print("O valor da hipotenusa é ", c)

"""# Exercício 7

Crie uma função que receba dois números ($n_1$ e $n_2$) e uma letra.

- Se a letra passada como parâmetro for "A", a função deve retornar a média aritmética entre os dois $\left(\frac{n_1+n_2}{2}\right)$
- Se a letra passada como parâmetro for "G", a função deve retornar a média geométrica entre os dois $\left(\sqrt{n_1+n_2}\right)$
- Se a letra passada como parâmetro for "H", a função deve retornar a média harmônica entre os dois $\left(\frac{2}{\frac{1}{n_1}+\frac{1}{n_2}}\right)$
- Se for passada qualquer outra letra, a função deve retornar 0

Fora da função, faça um programa que leia os dois números e uma letra, e imprima o resultado da chamada da função.
"""

import math

def funcao(n1, n2, letra): 
  if letra == "A" or letra == "a": 
    return (n1+n2)/2
  elif letra == "G" or letra == "g":
    return math.sqrt(n1+n2)
  elif letra == "H" or letra == "h": 
    return 2/((1/n1) + (1/n2))
  else: 
    return ("0")

n1 = int(input("Digite o primeiro número "))
n2 = int(input("Digite o segundo número "))
letra = str(input("Digite a letra "))

a = funcao(n1, n2, letra)

print(a)